import type { BuildSource } from "./types";

export const BUILD_SOURCES: BuildSource[] = [
  {
    id: "fh6-local-profiles",
    title: "FH6 Local Build Profiles",
    publisher: "FH6 Tune Companion knowledgebase",
    url: "",
    kind: "local",
    use: "Per-car archetype, likely roles, upgrade order, and avoid list.",
    limitation: "Derived from public source data and local rules; does not confirm exact upgrade availability or PI cost.",
    verified: "2026-06-11",
  },
  {
    id: "fh6-official-cars",
    title: "Forza Horizon 6 Cars List",
    publisher: "Forza / Playground Games",
    url: "https://forza.net/news/forza-horizon-6-cars-list",
    kind: "official",
    use: "Car identity and model years.",
    limitation: "Does not contain complete upgrade compatibility or PI costs.",
    verified: "2026-06-10",
  },
  {
    id: "fh6-official-seasons",
    title: "FH6 Japan Setting and Changing Seasons",
    publisher: "Xbox Wire / Playground Games",
    url: "https://news.xbox.com/en-us/2025/09/25/forza-horizon-6-japan-setting-2026/",
    kind: "official",
    use: "Confirms Spring, Summer, Autumn, Winter, hot summers, snowy winters, and meaningful seasonal world changes.",
    limitation: "Does not say that every event in a season has the same weather or road surface.",
    verified: "2026-06-11",
  },
  {
    id: "forzatune-guide",
    title: "Fully Updated Forza Tuning Guide",
    publisher: "ForzaTune",
    url: "https://forzatune.com/guide/the-fully-updated-forza-tuning-guide/",
    kind: "calculator",
    use: "Adjustable parts, weight balance, and explainable tuning principles.",
    limitation: "Commercial method; recommendations remain a starting point for testing.",
    verified: "2026-06-10",
  },
  {
    id: "forzatune-app",
    title: "ForzaTune Pro",
    publisher: "FlameFront Studios",
    url: "https://play.google.com/store/apps/details?id=com.flamefrontstudios.forzatune7",
    kind: "calculator",
    use: "FH6 support, required Race upgrades, and workflow comparison.",
    limitation: "FH6 is listed as beta and the formulas are not public.",
    verified: "2026-06-10",
  },
  {
    id: "forzafire-tires",
    title: "FH6 Tires & Rims Tuning Guide",
    publisher: "ForzaFire",
    url: "https://www.forzafire.com/guides/forza-horizon-6-tires-and-rims-tuning-guide",
    kind: "community",
    use: "Separates Rally Tires for Dirt from Off-Road Tires for Cross Country and documents the stronger dirt penalty for road compounds.",
    limitation: "General FH6 guidance; exact PI value and availability still vary by car.",
    verified: "2026-06-11",
  },
  {
    id: "forzafire-platform",
    title: "FH6 Platform & Handling Tuning Guide",
    publisher: "ForzaFire",
    url: "https://www.forzafire.com/guides/forza-horizon-6-platform-and-handling-tuning-guide",
    kind: "community",
    use: "Race Brakes priority, conservative ARB ranges, and handling upgrade trade-offs.",
    limitation: "General FH6 guidance; exact PI value and part availability vary by car.",
    verified: "2026-06-11",
  },
  {
    id: "quicktune-guide",
    title: "QuickTune Pro Build and Tuning Guides",
    publisher: "Fifty Inch",
    url: "https://forzaquicktune.com/guides/",
    kind: "calculator",
    use: "Build-assistant pattern: enter installed upgrades and flag unsuitable combinations.",
    limitation: "The public page did not confirm FH6 support when checked.",
    verified: "2026-06-10",
  },
  {
    id: "optn",
    title: "Open Tuning Project",
    publisher: "OPTN Club",
    url: "https://github.com/OPTN-Club/optn.club",
    kind: "community",
    use: "Open, inspectable build and tune data structures.",
    limitation: "Community source without a car-specific FH6 upgrade catalog.",
    verified: "2026-06-10",
  },
  {
    id: "forzalabs",
    title: "ForzaLabs Upgrade Guide",
    publisher: "Labs GG",
    url: "https://forza.labsgg.com/upgrade-guide",
    kind: "calculator",
    use: "Upgrade categories, trade-offs, and balancing power with handling.",
    limitation: "Exact build data and calculators require an account; no database was copied.",
    verified: "2026-06-10",
  },
  {
    id: "tune-it-yourself",
    title: "Tune It Yourself",
    publisher: "Pocket Playground",
    url: "https://www.tuneityourself.co.uk/",
    kind: "calculator",
    use: "Step-by-step testing for ride height, chassis, brakes, and gearing.",
    limitation: "FH6 support is unconfirmed; only the testing method informed this guide.",
    verified: "2026-06-10",
  },
  {
    id: "tunelab",
    title: "TuneLab 1.7.0",
    publisher: "super-android",
    url: "https://github.com/super-android/tunelab",
    kind: "community",
    use: "Mathematical baseline and public vehicle data.",
    limitation: "No complete upgrade catalog; its baseline is not final truth.",
    verified: "2026-06-10",
  },
  {
    id: "in-game",
    title: "Direct FH6 Verification",
    publisher: "Local verification",
    url: "",
    kind: "local",
    use: "Part availability, PI costs, final weight, and slider ranges.",
    limitation: "Must be confirmed per car and build.",
    verified: "ongoing",
  },
];
