import type { BuildSource } from "./types";

export const BUILD_SOURCES: BuildSource[] = [
  {
    id: "fh6-official-cars",
    title: "Forza Horizon 6 Cars List",
    publisher: "Forza / Playground Games",
    url: "https://forza.net/news/forza-horizon-6-cars-list",
    kind: "official",
    use: "Identiteit van auto's en modeljaren.",
    limitation: "Bevat geen complete upgradecompatibiliteit of PI-kosten.",
    verified: "2026-06-10",
  },
  {
    id: "forzatune-guide",
    title: "Fully Updated Forza Tuning Guide",
    publisher: "ForzaTune",
    url: "https://forzatune.com/guide/the-fully-updated-forza-tuning-guide/",
    kind: "calculator",
    use: "Verstelbare onderdelen, gewichtsbalans en uitlegbare tuningprincipes.",
    limitation: "Commerciële methode; adviezen blijven een startpunt voor praktijktests.",
    verified: "2026-06-10",
  },
  {
    id: "forzatune-app",
    title: "ForzaTune Pro",
    publisher: "FlameFront Studios",
    url: "https://play.google.com/store/apps/details?id=com.flamefrontstudios.forzatune7",
    kind: "calculator",
    use: "FH6-ondersteuning, benodigde race-upgrades en flowvergelijking.",
    limitation: "FH6 staat als beta vermeld; formules zijn niet openbaar.",
    verified: "2026-06-10",
  },
  {
    id: "quicktune-guide",
    title: "QuickTune Pro Build and Tuning Guides",
    publisher: "Fifty Inch",
    url: "https://forzaquicktune.com/guides/",
    kind: "calculator",
    use: "Build-assistpatroon: upgrades invoeren, ongeschikte combinaties waarschuwen.",
    limitation: "Publieke pagina bevestigt nog geen FH6-ondersteuning.",
    verified: "2026-06-10",
  },
  {
    id: "optn",
    title: "Open Tuning Project",
    publisher: "OPTN Club",
    url: "https://github.com/OPTN-Club/optn.club",
    kind: "community",
    use: "Open, controleerbare opbouw van build- en tunegegevens.",
    limitation: "Communitybron; geen autospecifieke FH6-catalogus.",
    verified: "2026-06-10",
  },
  {
    id: "forzalabs",
    title: "ForzaLabs Upgrade Guide",
    publisher: "Labs GG",
    url: "https://forza.labsgg.com/upgrade-guide",
    kind: "calculator",
    use: "Upgradecategorieën, trade-offs en het belang van balans tussen vermogen en handling.",
    limitation: "Exacte builddata en calculators vereisen een account; de database is niet overgenomen.",
    verified: "2026-06-10",
  },
  {
    id: "tune-it-yourself",
    title: "Tune It Yourself",
    publisher: "Pocket Playground",
    url: "https://www.tuneityourself.co.uk/",
    kind: "calculator",
    use: "Stapsgewijs testen per rijhoogte, onderstel, remmen en gearing.",
    limitation: "Geen bevestigde FH6-ondersteuning; alleen de testmethode is als inspiratie gebruikt.",
    verified: "2026-06-10",
  },
  {
    id: "tunelab",
    title: "TuneLab 1.7.0",
    publisher: "super-android",
    url: "https://github.com/super-android/tunelab",
    kind: "community",
    use: "Wiskundige baseline en openbare voertuigdata.",
    limitation: "Geen volledige upgradecatalogus; baseline is niet de eindwaarheid.",
    verified: "2026-06-10",
  },
  {
    id: "in-game",
    title: "Directe controle in FH6",
    publisher: "Eigen verificatie",
    url: "",
    kind: "local",
    use: "Beschikbaarheid, PI-kosten, eindgewicht en sliderbereiken.",
    limitation: "Moet per auto en build handmatig worden bevestigd.",
    verified: "doorlopend",
  },
];
